--enable-webrtc-pipewire-capturer
--enable-gpu-rasterization
--use-gl=angle --use-angle=gl
--enable-zero-copy
--no-pings
--enable-gpu-memory-buffer-video-frames
--disk-cache-dir=/dev/null
--video-capture-use-gpu-memory-buffer
--ozone-platform-hint=auto
--enable-features=WebRTCPipeWireCapturer,VaapiVideoEncoder,VaapiVideoDecodeLinuxGL,TouchpadOverscrollHistoryNavigation,CanvasOopRasterization,PlatformHEVCDecoderSupport,SplitCacheByNetworkIsolationKey,SplitCodeCacheByNetworkIsolationKey,SplitHostCacheByNetworkIsolationKey,PrefetchPrivacyChanges,IsolateSandboxedIframes,StrictOriginIsolation,PartitionConnectionsByNetworkIsolationKey,PartitionHttpServerPropertiesByNetworkIsolationKey,PartitionSSLSessionsByNetworkIsolationKey,PartitionNelAndReportingByNetworkIsolationKey,EnableCrossSiteFlagNetworkIsolationKey
--enable-native-gpu-memory-buffers
--extension-content-verification=enforce_strict
--extensions-install-verification=enforce_strict
